### ISSUE TITLE
Ability to add options after the poll's creation

### ISSUE THREAD

**Issue by abrahammurciano** [JohnnyJayJay/instant-poll#12]
It's very common for people to suggest other options to a poll after it's been asked. It would be great if there was a way to add new options after the poll's creation.

A possible way to implement this would be to have a button "Add Option" which would ask the person who clicked it to enter the new option.

Something to consider would be if anyone should be allowed to add an option or just the creator. Both should probably be possible with an option on creation to choose who's allowed.

**Comment by JohnnyJayJay** [comment]
That does sound like a decent idea, but I'm not sure whether it can be implemented properly. Arbitrary editing of interaction responses is very limited. 

Also, there's the conceptual issue of the existing votes. The previous votes become somewhat useless if you add an option the voters weren't presented with. So, should that simply be communicated through a comment in the message? How do you show which votes come from which set of options? While that doesn't rule out the feature entirely, I probably wouldn't enable it by default.

**Comment by abrahammurciano** [comment]
Although for polls where your goal is to accurately get an idea of people's opinions it would make the data inaccurate, there are other types of polls where this doesn't matter.

For example if the poll is being used to decide on a meeting place, someone might suggest a new option after the poll's creation. Instead of having to create a new poll to consider that option, it would make more sense to add that option in dynamically and let you friends know that there's another option to consider, and they may update their votes accordingly. 

Another example, which is the one that caused me to open this issue, is when I started a poll in my school server to decide on a name for our school bot. I put in a few options which I had thought of, but when other people suggested new options I was unable to include those in the poll.

Although I agree with you that polls shouldn't be extendable by default, it would be great to have an option to allow that.

**Comment by JohnnyJayJay** [comment]
I'll see what I can do.

**Comment by abrahammurciano** [comment]
Never mind, I made my own poll bot that includes this feature (and quite some more). Take a look if you're interested.

https://github,.com/abrahammurciano/paul-bot

**Comment by JohnnyJayJay** [comment]
Implemented by #34
