### ISSUE TITLE
Add an option to only allow certain roles or admins to create polls

### ISSUE THREAD

**Issue by ZzBombardierzZ** [JohnnyJayJay/instant-poll#26]
I'm very happy to find a poll bot that has exactly the visual display and options I was looking for. However, I would really love it if I could control who can use the /poll create option.

**Comment by JohnnyJayJay** [comment]
Are you looking for something like being able to set a role that is required to create polls? Or more like a single permission that is required.

**Comment by ZzBombardierzZ** [comment]
I think the first option but I'm not quite sure what you mean by the second one.

**Comment by ZzBombardierzZ** [comment]
I would still want anyone to be able to vote, but only a certain role or roles allowed to create a poll.

**Comment by JohnnyJayJay** [comment]
> I'm not quite sure what you mean by the second one.

Something like "if they're allowed to create threads, they're allowed to create polls" (as an example). Similar to how the ability to close polls isn't tied to a specific role but the permission to delete messages. In this case however, it seems like allowing you to set a role that can create polls is the best way. 

This should be fairly easy to implement, I'll do it when I have time again.

**Comment by ZzBombardierzZ** [comment]
Anything like that would be great honestly. I just am hoping to get some way to control who can and can't create a poll

**Comment by JohnnyJayJay** [comment]
So, it seems like this will be added via a native Discord feature very soon:
![](https://cdn.discordapp.com/attachments/889939268733132870/936712850460786748/1._Management_-_Overall.png)

**Comment by ZzBombardierzZ** [comment]
Where did this image come from? I'd love to see upcoming updates to discord such as this

**Comment by JohnnyJayJay** [comment]
This came from the [Discord Developers](https://discord.gg/discord-developers) event last week. It's not entirely set yet when this will go live, but they've been working on it for the past couple of months.

**Comment by JohnnyJayJay** [comment]
This is now implemented by Discord. Server Settings -> Integrations -> Manage.
