### ISSUE TITLE
Unable to add Bot

### ISSUE THREAD

**Issue by angsaysroar** [JohnnyJayJay/instant-poll#28]
I have tried to add the bot to 2 different servers without success. When adding the bot, it lets me know the permissions granted and shows the authorized screen, but the bot does not appear in the server.

I appreciate any assistance you can provide. Thank you!

**Comment by JohnnyJayJay** [comment]
Quoting from the readme/the top.gg page right at the beginning:

> You will notice that, when you've authorised the app, it will not join your server. This is intended, you can use the commands anyway. You can verify this by typing /poll info.
