### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by JohnnyJayJay** [JohnnyJayJay/instant-poll#3]
Currently, you can only set 5 options, but it only requires a fairly small change to allow for more than twice as many. 

- Commands can have up to 25 options
- Messages can have up to 25 components
- 1 Component is reserved for "Close Poll"
- 3 options are taken by `question`, `multi-vote` and `close-in`

It follows that the current maximum number of options is 22. I would suggest to use 15 or 20 instead, though; that way there is a buffer of at least 2 unused command options, in case we want to add more. Also, it means that the components can be aligned nicely, as they are in groups of 5. It also means that there are additional slots for other non-option buttons that may be added some time in the future.

**Comment by Eye-Sacc** [comment]
@JohnnyJayJay  Is this fix likely to happen any time soon? This would be my favorite poll bot if I had 15 possible answers available...

**Comment by JohnnyJayJay** [comment]
> @JohnnyJayJay  Is this fix likely to happen any time soon? This would be my favorite poll bot if I had 15 possible answers available...

I currently don't have much time and I'm on vacation, but I think I can manage to do this mid January.

**Comment by Eye-Sacc** [comment]
> > @JohnnyJayJay  Is this fix likely to happen any time soon? This would be my favorite poll bot if I had 15 possible answers available...
> 
> I currently don't have much time and I'm on vacation, but I think I can manage to do this mid January. 

Great, thanks!

**Comment by JohnnyJayJay** [comment]
Implemented by #14 . Will go live soon

**Comment by Eye-Sacc** [comment]
Sweet. Thanks!
-------- Original message --------From: Johnny ***@***.***> Date: 1/13/22  5:04 AM  (GMT-06:00) To: JohnnyJayJay/instant-poll ***@***.***> Cc: Eye-Sacc ***@***.***>, Manual ***@***.***> Subject: Re: [JohnnyJayJay/instant-poll] Add more options (#3) 
Implemented by #14 . Will go live soon
