### ISSUE TITLE
Only users with the <@&> role are allowed to vote

### ISSUE THREAD

**Issue by RobJ2210** [JohnnyJayJay/instant-poll#36]
Hello am using these settings /poll create question:Should we remove Skill Tree 1:Yes 2:No show-votes:Votes are not visible 

But my users and me are blocked from voting    https://gyazo.com/aba7da0072eccf59ff94b88db2301f82   Only users with the <@&> role are allowed to vote.

**Comment by JohnnyJayJay** [comment]
Thank you for reporting this! This is a major bug I overlooked when I pushed the update recently. I will fix it immediately.

**Comment by JohnnyJayJay** [comment]
Should be fixed now! Sorry for the inconvenience.
