### ISSUE TITLE
Mobile not working: "Invalid Form Body"

### ISSUE THREAD

**Issue by DaleBall2** [JohnnyJayJay/instant-poll#37]
Hello, I'm inquiring about a bug I found with an error message saying "Invalid Form Body" when I go to vote on my mobile smartphone (Android 12+ Galaxy S21 Ultra). Let me know if there's any advice you have for me in resolving this conflict I am having. Thanks for such an amazing mod!

![Screenshot_20220518-094957_Discord](https://user-images.githubusercontent.com/43657230/169072415-5d67c677-e2f4-4581-98d9-e764a2946617.jpg)

**Comment by JohnnyJayJay** [comment]
This is a bug in Discord mobile, not Instant Poll. It should be fixed in the latest version, check if your Discord is up to date. Otherwise, report this to Discord.

**Comment by DaleBall2** [comment]
Thanks! That was the problem.. Discord wasn't auto-updating.. the app for some reason wouldn't let me update manually either, I had to reinstall completely

**Comment by JohnnyJayJay** [comment]
Glad you got it sorted out :+1:
