### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by Road-block** [JohnnyJayJay/instant-poll#39]
This is __by far__ the best single purpose bot in the slash era for adding polls to your discord guild.

Long may it live.

I went looking for alternatives when my full-featured pre-slash bot stopped working. 
Was amazed by how many of the most popular "poll bots" are glorified embed creators with a few reactions attached.
There's a few *decent* ones but they either lack features (no anonymized polls, no timed close, no multiple selection, no aggregates) or advertise features that do not actually work.

Instant-poll is a breath of fresh air.

Good job.

**Comment by JohnnyJayJay** [comment]
Thank you for the kind words!
