### ISSUE TITLE
Add open polls

### ISSUE THREAD

**Issue by JohnnyJayJay** [JohnnyJayJay/instant-poll#9]
Currently, you can't see which users voted for which option(s). This could be added (as an optional setting) by keeping a list of voters in the message itself and updating it with every vote. This has a few problems:
- Message length is limited
- It is impossible to reliably align and format messages (relevant for when there are a lot of options)
- When a lot of people vote at the same time, the message length would change and it would become more difficult for other people to hit the (correct) buttons

As an alternative, I'm currently thinking about providing a tiny web interface where you can see the results of a poll (in addition to the simple message bar chart). This would be a rather large addition: I would need to make a nice-looking frontend, add websockets and routing as well as a few other things potentially. But I could see this becoming a feature in the future.

**Comment by bristermitten** [comment]
Perhaps a command like `/poll info <id>` could be used that will show the results of a poll in an embed or something. Would be easier than a web interface

**Comment by JohnnyJayJay** [comment]
An even better alternative might be a "View Votes" button that shows you the votes when clicked. Everybody can click it at any time to see the votes in an ephemeral message.

**Comment by shelbyvcobra** [comment]
This idea would make the bot great for doing polls for who is available when or preferred location

**Comment by JohnnyJayJay** [comment]
> This idea would make the bot great for doing polls for who is available when or preferred location

I've got it on my radar and will work through most issues and feature requests here next month :)

**Comment by JohnnyJayJay** [comment]
Closed by #16
